repositories:
  - name: stable
    url: https://charts.helm.sh/stable

releases:
  - name: dev
    namespace: dev
    chart: ./hello-chart
    values:
      - ./hello-values/dev.yaml

  - name: stage
    namespace: stage
    chart: ./hello-chart
    values:
      - ./hello-values/stage.yaml